### ISSUE TITLE
[Project Addition]: HTML, CSS and Javascript

### ISSUE THREAD

**Issue by hariketsheth** [ImBIOS/simple-web-project-collection#9]
# Description
- Would like to contribute to your repository with Projects for (Begineers) especially
- At Present, would like to add 5 Projects
   1. Project 1: Progressive Steps
   2. Project 2: Feedback System
   3. Project 3: Game of ASCII
   4. Project 4: CSS Loader
   5. Project 5: Form Animation
 
- Will update the README accordingly

**Comment by mrbyyn** [comment]
Great! No need to create a new issue for a new PR. But, for thia time, no problem. Happy Hacktober!
